# name: GitHub Actions Demo
# run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
# on: [push]
# jobs:
#   Explore-GitHub-Actions:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
#       - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#       - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#       - name: Check out repository code
#         uses: actions/checkout@v4
#       - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
#       - run: echo "🖥️ The workflow is now ready to test your code on the runner."
#       - name: List files in the repository
#         run: |
#           ls ${{ github.workspace }}
#       - run: echo "🍏 This job's status is ${{ job.status }}."
      
name: Deploy to our server

on:
  push:
    branches:
      - main
      - ilya-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to remote server
      run: scp -r ./* root@165.232.118.63:/root/kirill_tmp
      
    - name: SSH command
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: run Docker container
      run: |
        docker ps -q | xargs -r docker stop
        docker run -i -t -e TELEGRAM_BOT_TOKEN=$(TELEGRAM_BOT_TOKEN) -e OPENAI_API_KEY=$(OPENAI_API_KEY) $(IMAGE)
        
    # - name: Run command on remote server
    #   run: |
    #     ssh username@remote-server-ip "command-to-run-on-remote-server"

# Не забудьте заменить username, remote-server-ip и path/to/destination/folder на соответствующие 
# значения вашего удаленного сервера. Также необходимо добавить приватный ключ SSH в secrets репозитория 
# с названием SSH_PRIVATE_KEY.
